---
- name: Install Apache on CentOS 8
  hosts: localhost
  become: true               
  
  tasks:
    - name: Install Apache
      package:
        name: httpd           
        state: present        

    - name: Start Apache
      service:
        name: httpd           
        state: started        
        enabled: yes          
